# -*- coding: utf-8 -*-
"""MLPractical08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VEVjWrUOrAiaNMeiHQxPHFhwipEi7_Iu
"""

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

prk_ds = pd.read_csv('/content/parkinsons.data')

prk_ds.info()

from sklearn.model_selection import train_test_split

X = prk_ds.drop(columns=['name','status'],axis=1)
Y = prk_ds['status']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=2)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X_train,Y_train)

y_pred = rf.predict(X_test)

from sklearn.metrics import roc_curve,auc
false_positive_rate,true_positive_rate,thresholds = roc_curve(Y_test,y_pred)
roc_auc = auc(false_positive_rate,true_positive_rate)
roc_auc

