# -*- coding: utf-8 -*-
"""MLPractical02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1geKIrLazSMyAHEIM8fgStnNQ9rOre_Wc
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import datasets
import seaborn as sns
from sklearn import tree

df = pd.read_csv('/content/titanic.csv')

df.head()

df.describe()

sns.heatmap(df.corr(),cmap='YlGnBu')

df.isnull().sum()

df = df.drop(columns=['Name','Cabin'],axis=1)

df.isnull().sum()

df['Age'].fillna(df['Age'].mean(),inplace=True)

df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)

df.isnull().sum()

df.replace({'Sex':{'male':0,'female':1},'Embarked':{'S':0,'C':1,'Q':2}},inplace=True)

df = df.drop(columns=['PassengerId','Ticket'],axis=1)

df.head()

input = df.drop(columns=['Survived'],axis=1)
target = df['Survived']

print(input)

print(target)

model = tree.DecisionTreeClassifier()

model.fit(input,target)

model.score(input,target)

predictions = model.predict([[3,0,22,1,0,7.25,0]])

if(predictions==0):
  print('Survived')
else:
  print('Died')