# -*- coding: utf-8 -*-
"""MLPractical05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VAF3uP3Vo7sj4RZvggRmCkdQVkqT-7S1
"""

pip install scikit-surprise

import pandas as pd

from surprise import Dataset, Reader
from surprise import SVD
from surprise.model_selection import cross_validate

# Sample data (replace this with your movie ratings dataset)
data = [
    ('User1', 'Movie1', 4.0),
    ('User1', 'Movie2', 3.5),
    ('User2', 'Movie1', 5.0),
    ('User2', 'Movie2', 2.0),
    # Add more ratings here
]

# Load data into Surprise's Dataset format
reader = Reader(rating_scale=(1, 5))
movie_data = Dataset.load_from_df(pd.DataFrame(data, columns=['user_id', 'movie_id', 'rating']), reader)

# Use SVD algorithm (Matrix Factorization)
model = SVD()

# Train the model
model.fit(movie_data.build_full_trainset())

# Make predictions (for example, for User1)
user_id = 'User1'
movie_id = 'Movie2'
predicted_rating = model.predict(user_id, movie_id).est
print(f"Predicted rating for {user_id} on {movie_id}: {predicted_rating}")

