# -*- coding: utf-8 -*-
"""Practical01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wONWe6tn3mDcd8hJeScYIB0CXe1UmMco
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import datasets

iris_dataset = datasets.load_iris()

features = iris_dataset.data
labels = iris_dataset.target

print(features[0],labels[0])

print(labels)

import matplotlib.pyplot as plt

_, ax = plt.subplots()
scatter = ax.scatter(iris_dataset.data[:, 0], iris_dataset.data[:, 1], c=iris_dataset.target)
ax.set(xlabel=iris_dataset.feature_names[0], ylabel=iris_dataset.feature_names[1])
_ = ax.legend(
    scatter.legend_elements()[0], iris_dataset.target_names, loc="lower right", title="Classes"
)

print(iris_dataset.DESCR)

"""0 -> Setosa
1 -> Versicolor
2 -> Veronica
"""

classifier = KNeighborsClassifier()

classifier.fit(features,labels)

predictions = classifier.predict([[5.1 ,3.5 ,1.4 ,0.2]])

if(predictions == 0):
  print('Setosa')
elif(predictions == 1):
  print('Versicolor')
else:
  print('Veronica')

